prefix = "./corpora"
stop-words = "./corpora/stopwords.txt"

dataset = "lectures"
corpus = "lectures-file.toml"
index = "./corpora/lectures/idx"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
